#!/usr/bin/sh

#pandoc -t revealjs  -s -o index.html index.md -V revealjs-url=./reveal.js --slide-level=3 -V theme=moon  --include-in-header=custom.css 
#pandoc -t revealjs  -s -o index.html index.md -V revealjs-url=./reveal.js --slide-level=3 -V theme=moon  --css="custom.css"
pandoc -s -t revealjs -V revealjs-url=https://unpkg.com/reveal.js/  -o presentation.html research_questions_guide.md --slide-level=3 -V theme==moon --css="custom.css"
